import * as vscode from 'vscode';

import type { Config, LCDFilter, PetId } from "../types";
import { ADULT, BABY_1, BABY_2, CHILD, EGG, LCD_FILTER_NONE, PERFECT, ULTIMATE, ULTIMATE_PLUS } from '../types';
import { CONFIG_DISCOVER_MODE, CONFIG_EXCLUDE_PETS, CONFIG_EXPERIENCE_EVOLUTION_ADULT, CONFIG_EXPERIENCE_EVOLUTION_BABY_1, CONFIG_EXPERIENCE_EVOLUTION_BABY_2, CONFIG_EXPERIENCE_EVOLUTION_CHILD, CONFIG_EXPERIENCE_EVOLUTION_PERFECT, CONFIG_EXPERIENCE_EVOLUTION_ULTIMATE, CONFIG_EXPERIENCE_EVOLUTION_ULTIMATE_PLUS, CONFIG_EXPERIENCE_MULTIPLIERS_ACTIVE, CONFIG_EXPERIENCE_MULTIPLIERS_CURSOR_STEP, CONFIG_EXPERIENCE_MULTIPLIERS_ERROR_REMOVED, CONFIG_EXPERIENCE_MULTIPLIERS_FILE_CHANGE, CONFIG_EXPERIENCE_MULTIPLIERS_FILE_SAVE, CONFIG_EXPERIENCE_MULTIPLIERS_FILE_SAVE_STREAK, CONFIG_EXPERIENCE_MULTIPLIERS_GIT_BRANCH, CONFIG_EXPERIENCE_MULTIPLIERS_GIT_COMMIT, CONFIG_EXPERIENCE_MULTIPLIERS_GIT_MERGE, CONFIG_EXPERIENCE_MULTIPLIERS_LINES, CONFIG_EXPERIENCE_MULTIPLIERS_TERMINAL_BUILD_OR_TEST, CONFIG_EXPERIENCE_MULTIPLIERS_TERMINAL_COMMAND, CONFIG_EXPERIENCE_MULTIPLIERS_TERMINAL_TESTS_PASSED, CONFIG_EXPERIENCE_MULTIPLIERS_TYPING, CONFIG_EXPERIENCE_MULTIPLIERS_TYPING_STREAK, CONFIG_EXPERIENCE_MULTIPLIERS_WARNING_REMOVED, CONFIG_LCD_FILTER, CONFIG_RANDOM_EGGS, EVOLUTION_EXP_CONDITION_BY_LEVEL, NAMESPACE } from '../constants';
import { ACTIVE_XP_AMOUNT, COMMIT_XP, MERGE_XP, NEW_BRANCH_XP, SAVE_STREAK_BONUS_XP, SAVE_XP, STREAK_BONUS_XP, TESTS_PASSED_XP, XP_BUILD_TEST, XP_PER_CHARS_STEP, XP_PER_COMMAND, XP_PER_CURSOR_STEP, XP_PER_ERROR_REMOVED, XP_PER_FILE_CHANGE, XP_PER_LINES_STEP, XP_PER_WARNING_REMOVED } from '../trackers/constants';


export class ConfigManager {

  private config: Config;

  constructor() {
    this.config = this.loadConfig();
  }

  loadConfig() {
    const config = vscode.workspace.getConfiguration(NAMESPACE);

    return {
      lcdFilter: config.get<LCDFilter>(CONFIG_LCD_FILTER) ?? LCD_FILTER_NONE,
      excludePets: config.get<PetId[]>(CONFIG_EXCLUDE_PETS) ?? [],
      randomEggs: config.get<boolean>(CONFIG_RANDOM_EGGS) ?? false,
      discoverMode: config.get<boolean>(CONFIG_DISCOVER_MODE) ?? false,
      experience: {
        evolutionConditions: {
          [EGG]: 0,
          [BABY_1]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_BABY_1) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[BABY_1],
          [BABY_2]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_BABY_2) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[BABY_2],
          [CHILD]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_CHILD) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[CHILD],
          [ADULT]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_ADULT) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[ADULT],
          [PERFECT]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_PERFECT) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[PERFECT],
          [ULTIMATE]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_ULTIMATE) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[ULTIMATE],
          [ULTIMATE_PLUS]: config.get<number>(CONFIG_EXPERIENCE_EVOLUTION_ULTIMATE_PLUS) ?? EVOLUTION_EXP_CONDITION_BY_LEVEL[ULTIMATE_PLUS],
        },
        multipliers: {
          active: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_ACTIVE) ?? ACTIVE_XP_AMOUNT,
          errorRemoved: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_ERROR_REMOVED) ?? XP_PER_ERROR_REMOVED,
          warningRemoved: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_WARNING_REMOVED) ?? XP_PER_WARNING_REMOVED,
          cursorStep: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_CURSOR_STEP) ?? XP_PER_CURSOR_STEP,
          fileChange: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_FILE_CHANGE) ?? XP_PER_FILE_CHANGE,
          gitCommit: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_GIT_COMMIT) ?? COMMIT_XP,
          gitBranch: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_GIT_BRANCH) ?? NEW_BRANCH_XP,
          gitMerge: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_GIT_MERGE) ?? MERGE_XP,
          fileSave: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_FILE_SAVE) ?? SAVE_XP,
          fileSaveStreak: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_FILE_SAVE_STREAK) ?? SAVE_STREAK_BONUS_XP,
          terminalCommand: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_TERMINAL_COMMAND) ?? XP_PER_COMMAND,
          terminalBuildOrTest: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_TERMINAL_BUILD_OR_TEST) ?? XP_BUILD_TEST,
          terminalTestsPassed: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_TERMINAL_TESTS_PASSED) ?? TESTS_PASSED_XP,
          typing: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_TYPING) ?? XP_PER_CHARS_STEP,
          lines: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_LINES) ?? XP_PER_LINES_STEP,
          typingStreak: config.get<number>(CONFIG_EXPERIENCE_MULTIPLIERS_TYPING_STREAK) ?? STREAK_BONUS_XP,
        }
      }
    };
  }

  getConfig() {
    return this.config;
  }

  setConfig(config: Config) {
    this.config = config;
  }
}